// DECK BUILD
// ACE HIGH

cards = ["AofS", "1ofS" "2ofS" "3ofS" "4ofS" "5ofS" "6ofS" "7ofS" "8ofS" "9ofS" "JofS" "QofS" "KofS"];

// SPLIT THE DECK

// PLACING OF EACH PLAYERS CARD

// HIGHER CARD WINS

// CARDS BEING PLACED BACK TO STACK OF WINNING PLAYER

// WAR GAME _____------_____-----______----______-----

// PLACEMENT OF 3 CARDS FROM EACH PLAYERS STACK FACE DOWN

// PLACE OF 1 CARD UP FROM EACH STACK

// WINNER

// TIE OR REPEAT

// COLLECTION OF CARDS AFTER WIN

// END OF WAR GAME____-----______----____-----

// PLAYER'S CARDS REACH 0

// COUNTING OF ROUNDS
var rounds = function round() {};

// COUNTING OF WAR ROUNDS

// COUNTING OF BOTH ROUNDS TOTAL
