// DECK BUILD
// ACE HIGH

// SPLIT THE DECK

// PLACING OF EACH PLAYERS CARD

// HIGHER CARD WINS

// CARDS BEING PLACED BACK TO STACK OF WINNING PLAYER

// WAR GAME _____------_____-----______----______-----

// PLACEMENT OF 3 CARDS FROM EACH PLAYERS STACK FACE DOWN

// PLACE OF 1 CARD UP FROM EACH STACK

// WINNER

// TIE OR REPEAT

// COLLECTION OF CARDS AFTER WIN

// END OF WAR GAME____-----______----____-----

// PLAYER'S CARDS REACH 0

// COUNTING OF ROUNDS

// COUNTING OF WAR ROUNDS

// COUNTING OF BOTH ROUNDS TOTAL
